name: Monthly Manga Scraper

on:
  schedule:
    - cron: '0 0 1 * *'  # Exécuter à minuit le premier de chaque mois

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyppeteer beautifulsoup4 asyncio requests 

    - name: Run scraper script
      run: python test.py

    - name: Upload JSON as asset
      uses: actions/upload-artifact@v2
      with:
        name: planning
        path: planning.json
